# Generated by Django 4.1.3 on 2022-11-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tracker_status_alter_tracker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.trackerstatus', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.trackertype', verbose_name='Tip'),
            preserve_default=False,
        ),
    ]
