# Generated by Django 4.1.3 on 2022-11-22 10:23

from django.db import migrations

# def transfer_tags(apps, schema_editor):
#     Tracker = apps.get_model('webapp.Tracker')
#     for task in Tracker.objects.all():
#         task.type.set(task.type_old.all())
#
#
#
#
#
# def rollback_transfer(apps, schema_editor):
#     Tracker = apps.get_model('webapp.Tracker')
#     for task in Tracker.objects.all():
#         task.type_old.set(task.type.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_tracker_type_alter_tracker_type_old'),
    ]

    operations = [
        # migrations.RunPython(transfer_tags, rollback_transfer)
    ]
