# Generated by Django 4.1.3 on 2022-11-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_tracker_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_status', to='webapp.trackerstatus', verbose_name='Status'),
        ),
    ]
