# Generated by Django 4.1.3 on 2022-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_tracker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='status',
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.ManyToManyField(null=True, related_name='tasks_status', to='webapp.trackerstatus', verbose_name='Status'),
        ),
    ]
